# Generated by Django 4.2.3 on 2023-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
