# Generated by Django 4.2.3 on 2023-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_advocate_name_advocate_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
