# Generated by Django 4.2.3 on 2023-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_advocate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(null=True, verbose_name='Twitter'),
        ),
    ]
